language: node_js
node_js:
- 10.22
deploy:
  provider: elasticbeanstalk
  access_key_id: qqK6ayGo0hGcWHXAzw7edVVxT8TbMBWpteuxzmW0mVFnPTp6UvN0b0gvLneDf1wTFINaVBgrHZksIg11gOBMCyMBVD84qM2vMz3iwdoudWqm2jBmLNAcdnYHywTPqPXuECaI7KdcLPjWFLZRiM1QUdSm4quesHogskTUbTWKVzJ4n7a3iTVek+ZhPXCZuxYp/hPYtoo9wyHHZWtSbw+bTZ9Dm1piV9CXhy/i8l89Rq4e12D2BqQn65DTU/4uKbnJsjIxDoANEHmJPVJ4JkETY7Advm7y7iEDpyBR3V6ghDyo5YHv3S2R6BJ2oAm0bPsaaRrdZCOtwnD9pcg+cX+BYaD6xJ1Tahuae8Eah0mDx7eH7nP3fNMYFjRS1CscIBJZn2LJn4CCVCG6J1ei9wyL1bJb5jcPXIfxbLLnrVWgfSrnJXoBeVJOEMqrGYHFP8gwQD/YZK3JYMfqd7/RsgrfUa92W+fNoB4f5ryS5Fi/ASO1vMa/XGBSm3rwtLsm+N5cpOb18JVl1GYiTW9KosUnhxhgNc3QJ4I8xKloReNi1ZDJB72VElt+GdepjnYhHKj+0V//JCbB29Z2pJOHz+/hK3bLzdO0cVV4CKLsPZN81G3kbthnDcwLLmOfuTxJpdwhWzpAWKbiKuCXl5QIVskG1shCoHw7UEv7R4XrzrTJR+c=
  secret_access_key: NQGrtptwl+ixKdzC1k+Ip+p5lW6/axJOWFnfI5yWeRfz3sHusih4yzxVgEDZEXakjsw2lPIAVuI8Pn/VnxvZZj11pSKklyTUlNFdqgpNiWlaiAPg2sWTno0grM+D8bzIeoxAGv/dO8j1o4RaQ2z6ZLTDRduWPxtnJoVnn0OabvNX5yYZ7inrFHUWPo/gZ/9b9V99yFdFRDNxnspbzHDnIn9ZUQyasECmnu/CiiwscycTvtBOgFJCVnO6JqzDbpKYhMDQyjeX3hQiUg3L3j6cCc49XXvCOoaPfU5ZqId0fHZWWEoXZOMsGp3lXlYL1rwnSK7usris1NZ6PA5ro+vl7k1DKL/7Vqe2TNp5fQNJTSPkFlYJhWv+RLcLm+WvWjixaE0V+/G2czo32KnOYrhO7ZOubqvJCiuwg7rxvus+C/yfIYlvKPyUyiYps2Xvpbs5Y5g/FxvO0rl7BNNwIDr7hDkRg5qzsxJrrBaIzFemWd/Bx+QrAfSy9yrVCu1Qzti4tw+Ni3NM1s482acOQih4H0tpHCU0NZn+jnag5tQUgr0yRDJ25skaN60Ha5cwClEHidz0JW+rcWOnu2iY15yWZ7G9Cq3ea0sKUM8C/fTWRtWu0zuY59OSVMNw7TJDzqGb8FU04E97ad1ORn861QOxvoo2KWivzFHgkuObnok0Nhg=
  region: eu-central-1
  app: messages-app
  env: MessagesApp-env
  bucket_name: elasticbeanstalk-eu-central-1-823514127427
  on:
    repo: Akus/tdd-express-mocha-chai
  skip_cleanup: 'true'
