language: node_js
node_js:
- 10.22
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: gjQzWIXVBscTpzBaxSK/ZzElDotUr7sHpJUghN2NYY/UC7lSbLqrocKMYnJNVuavz87zq/4ueVtlC0Ynooe4blNS7+fnp8Rb0DPp66SYkCBgDlggz8HH5F74Wf0DlGFqblQpQk+PosulC6Mt3xV4ejikZzD6y7Byw+kdD8rc5AEsyIkiy9P+zwwuKlg1CB3AQoeVdqNB/Gr6zCoxM/5Y+kMmuevlbEAjIDhrbQs7cQ790l2tUow9rlMpOyeNHhbgaVt9ddHSFTw1dc+OeMuInT+6FBfDGQ9KdXu2RsU+D7LtFWVBo0ty6ba0nLYrAnoXqy4RP2U6UNtyGbC4UQpV/hDIXf4Yxe21T18Aihd1ep62OPNWNLeG3GV/22Ta97DMdVFW7lbT4slFC4MsRNLLthCnYgymO268vbJ4kosyGogPRlgW+ICevIGtpDgzIU1PDk6MRAuW5wBsVQlbV8Z1EWDLkRPXJ7qzp6zM+JLgS27VrTDMu5sWdxdFQOQVfTM2qcrv4lUlBdO2B5VHKEJT9RF31Tn7Pcz9sAIr6kPPYqCXVr9uCytzD4MZNfaDZKDeTZgvUFFG0efffCX1YFV4Hn3VDrgH0fgqtK7KakU3QUZiGKUYmBA8Gbf+4o6mBa8XXkli55CBczB7Ua3Rhl6y5lZUkLWjICnajP/3mmVEEZI=
  app: akos-message-app
  skip_cleanup: 'true'
