language: node_js
node_js:
  - 10.22
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAISBC3VLMF6YLNJTA
  secret_access_key: LK/sShp+qPXjBku01qCknXCjHrd1ToN7pRpvpnFKSLOorVQBD3ZuoYA9qW+i/+hiuWIB5pSZ1SeoOOpOH7SaC6VphZsuohTPR+d2L4HU3aqUrZabMvChiM80r6r8v2rb+/JKaY1+0bVAwkdsdrAXqVEGdv/6WKbp8PqbjpEOsqg3zUuc6+dKl9P0m5XB8D7qJHAzIffmWNqWrrgElySQeXXyYwGZ5PXPXIWVi9jPk5velQT1yjzH1/KnInYMSWKI0/Gsoy2WiFIx0dSmG/klv4+eFWX0CFWm6gB2e7XWqs/PDHWoZ5Nb2v/Y8O17kVTXGIhTatuc2SOVE1XqRbDoV864Cm7aTHYMvIGw6vDqEGjhETB9fe7nqgYebQm10b30sHEMxrNk28R9tP67CLaGixaD4LY7/u6B9QceCUD6Qjibv1c186rNhjOO98DcTr68+266hnd+auJ9q5Vw4LZ5W1C19rtA79iV15eEc/mjupg0Fyue+WoTlGAaI6Qg+bGyHMI37Encs9EZsbITWcYnUPOE0YgIoeNWpI3IoD21X9sRVIC6cuhak0UlN/nsDNQJ3OYphd0ek7y91lkIY69N8OOnYv6k/lONlm2CxPXA8vXC4r+OdKhoWX/1gRoM8qX24jEMye44GIsrF9KtilAkZA1zU9IOE9o4WBnavf/ukEE=
  region: eu-central-1
  app: musician-app
  env: MusicianApp-env
  bucket_name: elasticbeanstalk-eu-central-1-823514127427
  on:
    repo: Akus/tdd-express-mocha-chai
  skip_cleanup: 'true'
