language: node_js
node_js:
- 10.22
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIA37PKELRBRI2NDDEE
  secret_access_key: ibHrdS3uK6O7JEyALLG2kyzIe5gXQT26EfGvqZ5q16nBtByNN2LkVHODJTGNpLckxYGlDfrwyo+Gx0fEPIP+k5e6jlbOxbAVXqnMJr0Hi5AB1srWbsknV507rhbdd5XvqpVxq/Aytujqqi2yDWkKryJ05vQuE798vagwvqUAKCPFbPBuVGSlodjioiakFc2x/M4OJhp9rhIVTgW1VlKse+6nO5yC/h1GaSIzrommlbF3zvtz4i9BmfKKG5qFqbsD9xC710OwjEepdmXWWRIFXlGIpQOP7XUB/D2HI0ccFc2G0sFQwCU3LcJCvyeJLXglFDYSyY6mRFGPc8JfrapwY+g1ZRj769Q6oYjhnPXi6uuIJYvbiRTxgLDNpj/JuUqG0A6YOjvN65f76HfSEIe6Yx0yS2aaGRNuv3YsBJOyph2RWGijIyAVWergkfepSeZTQxcoxOMPN4VySrzUs2MhpjAojLlE/vAFpYwpgCeEOph8+ofVflecZ24y1/xlKYsZGpL/xN84RG8tmw5ByJKbhN76NAU8L2Oz8QH0NmICvCwG2M+nwd9JzUKG6kN1eZuk44k0LxsniyM++ZO2jVeaqrnJlKaMcRDAgsmNhrk9zlI0HM2iFRp1FypXKVSPdj7bAfja6vTeWZIAwUsbSTjfdnTeFmkQEwwPyvUmZdJQzzo=
  region: eu-central-1
  app: musician-app
  env: MusicianApp-env
  bucket_name: elasticbeanstalk-eu-central-1-823514127427
  on:
    repo: Akus/tdd-express-mocha-chai
  skip_cleanup: 'true'
