language: node_js
node_js:
- 10.22
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: UYd759jrM3IzvhXAzqHrimYfKn8K5PYYKNTo3NunxqxreJlFO+TVXt9I6MfL4QvyWHh03KuCugxUQrlZITD1Fzl5PkXUJmX15JDMYaUG6nITJPrxNtgYwDspQii4gUq7eyYJXs7WOdopbJTnZB1wfOhaSQtHS7ZOxq8JvX3EPV7T6cTp5B/TLrrJ8OhluJYdY+gazGc7HY2c0oC93yA+zZ9qaq5323X4b/DvEM+CO04J5Y91wjzc3MKZX610ZKPZbZX/NpJHwIbbtmLT0jQea4dZyfxzUF3rxFw4iE6fGpwy5Lg88HTiXKEmjLc9kHLGyfk0riGR8s9K4NVKVGjfGQhd5cYnFB/70iLaHU8wEkzOGagRoKDpAATgUU5a5bu+d3lEi9qy2m4Ow3lkSRvxEApGSfMc1KEDoBWx2ONGxsBGUqLbDznpoH4IReKFfVdi4sAGc2yvMBm5rifK9S7MyINwiNHU/UZHWARuAT/WXkJQ0vQgCf29WGqJjBP37zeBhPFLgNbhO36C/icdR44hH9ULCAAAJSPd4y4ZY6PTuM3qXXUT59HgB92+H0lFWLWzOmSxkQTuukvqgko4oKjKTKxsTKn1DY7hXs8FFzTLz1+4T8BpgscE9TFjvCp1248nA0Se3xBo2YSMNAOoyayADv+gcb0mIAF/TJxLbxPylU4=
  secret_access_key:
    secure: mNrgTJ1NLYoQV1hIC6IvUHuU5EF+GhZ7l2Ph92aIFo6ZTlw0jyeUuFCZee3Tt0gDNXcVPYqn637M0zrkRTALdpCAwtjJ567M7NX2kVnPVGWAMcfH30QtzFpcpzbUdNEJf1M/deWZSVBSlavqvwM5rwWJV29i9CnnbcWVKPj8/gGHVw8ZUMvFIeRxuLKlMZ/AQgoezX71k3xOsq4FJXa7VhwaHAAyTZKn3whMxDp00+/mr9lWgsiXCar8oOvKzpL70GiwOHhExr4lhQXGTqO1jwxz0DAP1wbUzIgyMqhDmmizh1BOLKAdsqDZeixlI3MiBqrYK1aZX4JmfRj+bBo81RuMPhcrwqrf4rW+zPFn0vz7k6cAWKHKYWdByrLDxk97k1HcpO5evNXm28AcmZ9mXwOFCRnfzGWai7XtH+o3wFTaiF0dKr//Wq8231TJRe9JGN+Bv/ilktGq0xsvduKVoUsg4AVzlubMXZs1rCXrvkqdOg9/wVSM6hBiwbHeWkziE+DiHhCb5sSq//JhmYozq2MAc5Wr2qQK5lOBc4EdnMGVjLvkEqYMVZcFwwoBaEyjSter3zuCUAOscNdZ6lKDt8SeNtxSSQ2I0SDha/Bue7lwHZRaHPUFaRCuBroFC4q+6QNHIKeL+IGEoDhvRCduxX9vt92ehd9IZWBh5hPnyWI=
  region: eu-central-1
  app: musician-app
  env: MusicianApp-env
  bucket_name: elasticbeanstalk-eu-central-1-823514127427
  on:
    repo: Akus/tdd-express-mocha-chai
  skip_cleanup: 'true'
